### ISSUE TITLE
python2 os has no attribute with link

### ISSUE THREAD

**Issue by focalism** [Prodesire/pydu#2]
When I use the link function(on windows) ,I have get an error:
`import os`
`os.link`
I get this:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'link'`

This may slove the problem:
https://github.com/kdwyer/apptrace/issues/8

**Comment by Prodesire** [comment]
Thanks for pointing that. According to [official document](https://docs.python.org/2/library/os.html#files-and-directories), os.link is only available on Unix.
